name: Samreen-Joy
favicon: null
layout_spectrum: 0.22028334951028228
typography_spectrum: 0.6818566971924156
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8926859579514712
  lightness: 0.2969941219780594
  saturation: 0.827664366690442
  rhythmicContrast: 0.6468642549589276
purpose: []
